### ISSUE TITLE
Cannot see moOde connect on 'devices available' in Spotify

### ISSUE THREAD

**Issue by pauljwhelan** [RafaPolit/moode-spotify-connect-web#14]
After building spotify-connect-web and starting both the avahi and spotify-connect services I get the followling messages each time I select the 'devices available' option in Spotify:

2020-03-26 14:16:26,066] ERROR in app: Exception on /login/_zeroconf [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 221, in login_zeroconf
    return get_info()
  File "main.py", line 251, in get_info
    'remoteName': zeroconf_vars['remoteName']
  File "/home/pi/.local/lib/python2.7/site-packages/flask/json.py", line 254, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/home/pi/.local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Request' object has no attribute 'is_xhr'
::ffff:192.168.1.25 - - [2020-03-26 14:16:26] "GET /login/_zeroconf?action=getInfo HTTP/1.1" 500 426 0.044331

After doing a few searches I found this: https://stackoverflow.com/questions/60131900/weird-is-xhr-error-when-deploying-flask-app-to-heroku which mentions an upgrade to the werkzurg python package which causes problems with versions of the flask package below 0.12.4. The suggestions for fixing this issue included upgrading to flask v1.0.0 and higher or downgrading werkzeug to below 1.0. 

As the requirements.txt includes the line Flask==0.11.1 I assumed there was a strict dependency on that version and so upgrading to V1 probably isn't a good idea so I added wekzeug<1.0, re-ran pip install -r requirements.txt, rebooted (not strictly necessarily but whatever), started both the services and now it works just fine.

**Comment by RafaPolit** [comment]
Thanks so much for this.  Indeed, `wekzeug <1.0` fixes the issue.  I have added this to the repo so that further downloads will not require this extra step.

I really appreciate the issue reporting.
