### ISSUE TITLE
Index out of Range

### ISSUE THREAD

**Issue by DanielKng** [RafaPolit/moode-spotify-connect-web#2]
As i try to use the Start Command:

`spotify-connect-web/spotify-connect-web --playback_device hw:1 -m PCM --mixer_device_index 1 --bitrate 320 --name "moOde Connect" --key spotify-connect-web/spotify_appkey.key`

in it's form provided by the Readme, i get this error:

> Loading Spotify library...
> Traceback (most recent call last):
>   File "loader.py", line 3, in <module>
>   File "runpy.py", line 180, in run_module
>   File "runpy.py", line 72, in _run_code
>   File "/home/pi/spotify/spotify-connect-web/main.py", line 14, in <module>
>     from connect import Connect
>   File "/home/pi/spotify/spotify-connect-web/connect.py", line 9, in <module>
>     from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
>   File "/home/pi/spotify/spotify-connect-web/console_callbacks.py", line 24, in <module>
>     audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
> IndexError: list index out of range
> Failed to execute script loader

I already tried changing the `mixer_device_index` to `0`, still the same.

Output of `aplay -L`:

> null
>     Discard all samples (playback) or generate zero samples (capture)
> crossfeed
> ladspa
> default:CARD=sndrpihifiberry
>     snd_rpi_hifiberry_dac,
>     Default Audio Device
> sysdefault:CARD=sndrpihifiberry
>     snd_rpi_hifiberry_dac,
>     Default Audio Device
> dmix:CARD=sndrpihifiberry,DEV=0
>     snd_rpi_hifiberry_dac,
>     Direct sample mixing device
> dsnoop:CARD=sndrpihifiberry,DEV=0
>     snd_rpi_hifiberry_dac,
>     Direct sample snooping device
> hw:CARD=sndrpihifiberry,DEV=0
>     snd_rpi_hifiberry_dac,
>     Direct hardware device without any conversions
> plughw:CARD=sndrpihifiberry,DEV=0
>     snd_rpi_hifiberry_dac,
>     Hardware device with all software conversions

I can't fix it, and need help. Thanks!

**Comment by RafaPolit** [comment]
It appears you do not have a hw:1 playback device.  Please try changing that to hw:0.

That perhaps also require the mixer to be 0, not sure about that.

My instructions are meant for USB DACs, I have no onboard DAC or other boards I can test this with! If we find a working scenario for your setup, we could add a case-by-case scenario to help others.

Let me know how it turns out.

Best regards,
Rafa.

**Comment by DanielKng** [comment]
Still no luck:

```
spotify-connect-web/spotify-connect-web --playback_device hw:0 -m Digital --mixer_device_index 0 --bitrate 320 --name "moOde Connect" --key spotify-connect-web/spotify_appkey.key      Loading Spotify library...
Traceback (most recent call last):
  File "loader.py", line 3, in <module>
  File "runpy.py", line 180, in run_module
  File "runpy.py", line 72, in _run_code
  File "/home/pi/spotify/spotify-connect-web/main.py", line 14, in <module>
    from connect import Connect
  File "/home/pi/spotify/spotify-connect-web/connect.py", line 9, in <module>
    from console_callbacks import audio_arg_parser, mixer, error_callback, connection_callbacks, debug_callbacks, playback_callbacks, playback_setup
  File "/home/pi/spotify/spotify-connect-web/console_callbacks.py", line 24, in <module>
    audio_arg_parser.add_argument('--mixer', '-m', help='alsa mixer name for volume control', default=alsa.mixers()[0])
IndexError: list index out of range
Failed to execute script loader
```

**Comment by RafaPolit** [comment]
Did you ever manage to get this sorted out?  You could try without hw:0 but the actual names? Or default?

Really not sure what else to try.

Best regards,
Rafa.
